static const char black[]       = "#1a1b26";
static const char gray2[]       = "#2b325c"; // unfocused window border
static const char gray3[]       = "#7aa2f7"; // focused window border
static const char gray4[]       = "#414868";
static const char blue[]        = "#E88FFF";
static const char green[]       = "#9ece6a";
static const char red[]         = "#f7768e";
static const char orange[]      = "#ff9e64";
static const char yellow[]      = "#e0af68";
static const char col_borderbar[]  = "#1a1b26"; // inner border
static const char white[]       = "#c0caf5";
