#!/bin/bash

# Pulls files from their home to dotfiles

cp "$HOME/.xinitrc" "$HOME/dotfiles/" && \
cp "$HOME/.config/alacritty/alacritty.toml" "$HOME/dotfiles/" && \
cp "$HOME/.config/chadwm/chadwm/config.def.h" "$HOME/dotfiles/" && \
cp "$HOME/.config/chadwm/chadwm/themes/tokyonight.h" "$HOME/dotfiles/" && \
cp "$HOME/.config/chadwm/scripts/bar.sh" "$HOME/dotfiles/" && \
cp "$HOME/.config/chadwm/scripts/run.sh" "$HOME/dotfiles/" && \
cp "$HOME/.config/chadwm/scripts/bar_themes/tokyonight" "$HOME/dotfiles/" && \
cp "$HOME/.config/rofi/config.rasi" "$HOME/dotfiles/" && \
cp "$HOME/.config/picom/picom.conf" "$HOME/dotfiles/"

echo "Dotfiles successfully pulled!"
