#!/bin/bash

# Pushes files from dotfiles to their home

cp "$HOME/dotfiles/.xinitrc" "$HOME/" && \
cp "$HOME/dotfiles/alacritty.toml" "$HOME/.config/alacritty/" && \
cp "$HOME/dotfiles/config.def.h" "$HOME/.config/chadwm/chadwm/" && \
cp "$HOME/dotfiles/tokyonight.h" "$HOME/.config/chadwm/chadwm/themes/" && \
cp "$HOME/dotfiles/bar.sh" "$HOME/.config/chadwm/scripts/" && \
cp "$HOME/dotfiles/run.sh" "$HOME/.config/chadwm/scripts/" && \
cp "$HOME/dotfiles/tokyonight" "$HOME/.config/chadwm/scripts/bar_themes/" && \
cp "$HOME/dotfiles/config.rasi" "$HOME/.config/rofi/" && \
cp "$HOME/dotfiles/picom.conf" "$HOME/.config/picom/"

echo "Dotfiles successfully pushed!"
