#!/bin/bash

# Pushes files from dotfiles to their home

cp /home/herminator/dotfiles/.xinitrc /home/herminator/ && \
cp /home/herminator/dotfiles/alacritty.toml /home/herminator/.config/alacritty/ && \
cp /home/herminator/dotfiles/config.def.h /home/herminator/.config/chadwm/chadwm/ && \
cp /home/herminator/dotfiles/tokyonight.h /home/herminator/.config/chadwm/chadwm/themes/ && \
cp /home/herminator/dotfiles/bar.sh /home/herminator/.config/chadwm/scripts/ && \
cp /home/herminator/dotfiles/run.sh /home/herminator/.config/chadwm/scripts/ && \
cp /home/herminator/dotfiles/tokyonight /home/herminator/.config/chadwm/scripts/bar_themes/ && \
cp /home/herminator/dotfiles/config.rasi /home/herminator/.config/rofi/ && \
cp /home/herminator/dotfiles/picom.conf /home/herminator/.config/picom/

echo "Dotfiles restored successfully!"
